### PR TITLE
Add go.mod

### PR DESCRIPTION
**Pull request by frederikhors**
I used these instructions:
- https://github.com/golang/go/wiki/Modules#how-to-define-a-module
- https://github.com/golang/go/wiki/Modules#how-to-prepare-for-a-release

We should tag `master` `v2.0.0`.

### CODE REVIEW

**Comment by aarondl** [comment]
Currently uninterested in having Go modules in the project. This is also an insufficient change as the import paths within the project I think also need to change to reflect the /v2 suffix.

**Comment by frederikhors** [comment]
> Currently uninterested in having Go modules in the project. This is also an insufficient change as the import paths within the project I think also need to change to reflect the /v2 suffix.

Nope. Is tested and everything is good. No import paths to update here.

**Comment by frederikhors** [comment]
Please reconsider, go modules are useful in CI.

**Comment by aarondl** [comment]
From your same source: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

> As a result of Semantic Import Versioning, code opting in to Go modules must comply with these rules:

> If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.1) and **in the package import path (e.g., import "github.com/my/mod/v2/mypkg")**. This includes the paths used in go get commands (e.g., go get github.com/my/mod/v2@v2.0.1. Note there is both a /v2 and a @v2.0.1 in that example. One way to think about it is that the module name now includes the /v2, so include /v2 whenever you are using the module name).

Go modules can still be used without having a go.mod, as it simply pins things to a given commit. It can still use tags, it can still use everything, the main difference is that the dependencies of the library are not specified which means that your project must specify them (they show up in your go.mod file as `//incompatible`). This is the behavior of the old `GOPATH` where you had to decide what version of a dependency to use.

**Pull request closed without merging**
